import type { Metadata } from "next";
import "./globals.css";
import { ShopProvider } from "../../context/ShopContext";

export const metadata: Metadata = {
  title: "Q2 hackathon UI clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ShopProvider>
        <body>{children}</body>
      </ShopProvider>
    </html>
  );
}
